name: Deploy Modbus App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh
          
          # Save SSH private key to file and set proper permissions
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add EC2 to known hosts to avoid SSH fingerprint prompt
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Run the SSH commands to deploy on EC2
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<EOF
          # Ensure the 'modbus-software-project' directory exists, clone it if not
          if [ ! -d "modbus-software-project" ]; then
            git clone https://github.com/knk-sys/modbus-software-project.git
          fi

          # Navigate to the project directory
          cd modbus-software-project

          # Pull the latest code
          git pull origin main

          # Ensure Python3 and pip3 are installed
          if ! command -v python3 &> /dev/null
          then
              echo "Python3 not found, installing..."
              sudo yum install -y python3
          fi

          if ! command -v pip3 &> /dev/null
          then
              echo "pip3 not found, installing..."
              curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
              sudo python3 get-pip.py
          fi

          # Install dependencies
          pip3 install -r requirements.txt

          # Kill any running instance of app.py
          pkill -f app.py || true

          # Run the application in the background
          nohup python3 app.py &
          EOF
